# Generated by Django 5.0 on 2024-03-13 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('available_seats_A', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_seats_B', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_seats_C', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_seats_D', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stadium_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_members', models.TextField()),
                ('home_ground', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.stadium')),
            ],
        ),
    ]
