# Generated by Django 5.0 on 2024-03-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbrevation',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
